groups:
- name: node_monitoring
  rules:
  - alert: NodeDown
    expr: up{job="nodes"} == 0
    for: 15s
    labels:
      severity: critical
    annotations:
      summary: "Node down (instance {{ $labels.instance}})"
      description: "{{ $labels.instance }} down for +15 seconds."